"""Дизайн дослідження: галузі, відстежувані бренди, домени брендів і запити двома мовами.

Шаблони брендів застосовуються без урахування регістру. Там, де назва збігається
зі звичайним словом («розетка», «цитрус», «подорожник»), фрагмент (?-i:...) вимагає великої літери.
"""

INDUSTRIES = {
    "bank": {
        "title": "Банки",
        "brands": {
            "ПриватБанк": r"приват\s?банк|приват\s?24|privat\s?bank|privat\s?24|\bприват(?:у|і|ом|а)?\b",
            "monobank": r"monobank|монобанк|\bmono\b|\bмоно\b",
            "Ощадбанк": r"ощадбанк|oschadbank|ощад\s?24|\bощад(?:у|і|ом|а)?\b",
            "Райффайзен Банк": r"райф+айзен|raif+eisen|\bрайф(?:у|і|ом|а)?\b",
            "ПУМБ": r"\bпумб|\bpumb\b|\bfuib\b|перш\w+ українськ\w+ міжнародн\w+ банк",
            "УкрСиббанк": r"укрсиб|ukrsib",
            "А-Банк": r"\bа-банк|\bабанк|\ba-bank|\babank",
            # Альфа-Банк Україна перейменовано на Sense Bank у 2022 році; моделі досі вживають стару назву.
            "Sense Bank": r"sense\s?bank|sense\s?superapp|сенс\s?банк|альфа[-\s]?банк|alfa[-\s]?bank",
            "Укргазбанк": r"укргазбанк|ukrgasbank|\bугб\b",
            "OTP Bank": r"\botp\b|\bотп\b|отіпі",
            "Укрексімбанк": r"укрексім|ukrexim|\bексімбанк",
            "Креді Агріколь": r"кред[іи]\s?агр[іи]кол|cr[eé]dit\s?agricole",
            "Кредобанк": r"кредобанк|kredobank",
        },
        "domains": {
            "ПриватБанк": ["privatbank.ua", "privat24.ua"],
            "monobank": ["monobank.ua"],
            "Ощадбанк": ["oschadbank.ua"],
            "Райффайзен Банк": ["raiffeisen.ua"],
            "ПУМБ": ["pumb.ua"],
            "УкрСиббанк": ["ukrsibbank.com"],
            "А-Банк": ["a-bank.com.ua"],
            "Sense Bank": ["sensebank.ua", "sensebank.com.ua", "alfabank.ua"],
            "Укргазбанк": ["ukrgasbank.com"],
            "OTP Bank": ["otpbank.com.ua"],
            "Укрексімбанк": ["eximb.com"],
            "Креді Агріколь": ["credit-agricole.ua"],
            "Кредобанк": ["kredobank.com.ua"],
        },
        "queries": [
            ("BEST", "Який банк в Україні найкращий?", "Which bank in Ukraine is the best?"),
            ("BEST", "Порадь надійний банк для зберігання заощаджень.", "Recommend a reliable bank for keeping my savings."),
            ("BEST", "Який мобільний банкінг в Україні найзручніший?", "Which mobile banking app in Ukraine is the most convenient?"),
            ("BEST", "Яку банківську картку варто оформити?", "Which bank card should I get?"),
            ("TASK", "Де відкрити рахунок ФОП?", "Where should I open a bank account as a sole proprietor (FOP)?"),
            ("TASK", "У якому банку краще взяти іпотеку?", "Which bank is better for getting a mortgage?"),
            ("TASK", "Де оформити кредитну картку з пільговим періодом?", "Where can I get a credit card with a grace period?"),
            ("TASK", "Який банк обрати для отримання переказів з-за кордону?", "Which bank should I choose for receiving money transfers from abroad?"),
            ("COMP", "Який онлайн-банк зручніший для щоденних платежів?", "Which online bank is more convenient for everyday payments?"),
            ("COMP", "Державний чи приватний банк — що краще обрати?", "A state-owned or a private bank — which is better to choose?"),
            ("COMP", "Який банк дає кращий кешбек?", "Which bank offers better cashback?"),
            ("COMP", "Який банк найкращий для малого бізнесу?", "Which bank is the best for a small business?"),
            ("PRICE", "У якому банку найвищі ставки за депозитами?", "Which bank has the highest deposit rates?"),
            ("PRICE", "Де найдешевше обслуговування рахунку ФОП?", "Where is the cheapest account servicing for a sole proprietor (FOP)?"),
            ("PRICE", "Який банк має найнижчу комісію за перекази?", "Which bank has the lowest transfer fees?"),
            ("PRICE", "Де найвигідніший курс обміну валют у застосунку?", "Which banking app has the best currency exchange rate?"),
            ("TRUST", "Які банки в Україні найнадійніші під час війни?", "Which banks in Ukraine are the most reliable during the war?"),
            ("TRUST", "У якому банку безпечно тримати велику суму?", "In which bank is it safe to keep a large sum of money?"),
            ("TRUST", "Який банк має найкращу службу підтримки?", "Which bank has the best customer support?"),
            ("TRUST", "Який банк найкраще захищає від шахраїв?", "Which bank protects customers from fraud best?"),
        ],
    },
    "ecom": {
        "title": "E-commerce",
        "brands": {
            "Rozetka": r"rozetka|(?-i:Розетк|РОЗЕТК)",
            "Prom.ua": r"\bprom\.ua|(?-i:\bProm\b|\bПром\b)|пром\.юа",
            "Епіцентр": r"epicent(?:r|er|re)|(?-i:Епіцентр|Эпицентр)",
            "Comfy": r"\bcomfy\b|(?-i:\bКомфі\b|\bКомфи\b)",
            "Фокстрот": r"фокстрот|foxtrot",
            "Allo": r"\ballo\b|(?-i:\bАЛЛО\b|\bАлло\b)",
            "MOYO": r"\bmoyo\b|(?-i:\bМОЙО\b|\bМойо\b)",
            "Kasta": r"\bkasta\b|(?-i:\bКаст[аиіу]\b)",
            "MAUDAU": r"maudau|маудау",
            "Цитрус": r"\bcitrus\b|\bctrs\b|(?-i:\bЦитрус)",
        },
        "domains": {
            "Rozetka": ["rozetka.com.ua"],
            "Prom.ua": ["prom.ua"],
            "Епіцентр": ["epicentrk.ua"],
            "Comfy": ["comfy.ua"],
            "Фокстрот": ["foxtrot.com.ua"],
            "Allo": ["allo.ua"],
            "MOYO": ["moyo.ua"],
            "Kasta": ["kasta.ua"],
            "MAUDAU": ["maudau.com.ua"],
            "Цитрус": ["ctrs.com.ua", "citrus.ua"],
        },
        "queries": [
            ("BEST", "Який інтернет-магазин в Україні найкращий?", "Which online store in Ukraine is the best?"),
            ("BEST", "Де краще купувати техніку онлайн?", "Where is it better to buy electronics online?"),
            ("BEST", "Порадь надійний маркетплейс.", "Recommend a reliable marketplace."),
            ("BEST", "Де зручно купувати товари для дому онлайн?", "Where is it convenient to buy home goods online?"),
            ("TASK", "Де купити ноутбук онлайн?", "Where can I buy a laptop online?"),
            ("TASK", "Де замовити смартфон з доставкою?", "Where can I order a smartphone with delivery?"),
            ("TASK", "Де купити побутову техніку в розстрочку?", "Where can I buy home appliances on an installment plan?"),
            ("TASK", "Де купити одяг онлайн з можливістю повернення?", "Where can I buy clothes online with the option to return them?"),
            ("COMP", "Маркетплейс чи спеціалізований магазин техніки — де краще купувати?", "A marketplace or a specialized electronics store — where is it better to buy?"),
            ("COMP", "Який інтернет-магазин має найшвидшу доставку?", "Which online store has the fastest delivery?"),
            ("COMP", "У якому магазині найкраща програма лояльності?", "Which store has the best loyalty program?"),
            ("COMP", "Де найбільший вибір електроніки?", "Where is the largest selection of electronics?"),
            ("PRICE", "Де найдешевше купити телевізор?", "Where is the cheapest place to buy a TV?"),
            ("PRICE", "У якому інтернет-магазині найкращі знижки?", "Which online store has the best discounts?"),
            ("PRICE", "Де вигідно купити техніку на «чорну п'ятницю»?", "Where can I get good Black Friday deals on electronics?"),
            ("PRICE", "Де безкоштовна доставка замовлень?", "Which stores offer free delivery of orders?"),
            ("TRUST", "Яким інтернет-магазинам можна довіряти?", "Which online stores can be trusted?"),
            ("TRUST", "Де купити оригінальну техніку з офіційною гарантією?", "Where can I buy genuine electronics with an official warranty?"),
            ("TRUST", "Який магазин без проблем повертає гроші?", "Which store refunds money without hassle?"),
            ("TRUST", "Де безпечно платити карткою онлайн?", "Where is it safe to pay by card online?"),
        ],
    },
    "pharma": {
        "title": "Аптеки",
        "brands": {
            "Аптека 9-1-1": r"9[-\s]?1[-\s]?1|apteka\s?911",
            "Подорожник": r"podorozhn[iy]k|(?-i:Подорожник)",
            "АНЦ": r"аптек\w* низьких цін|apteka nyzkykh tsin|pharmacy of low prices|low[- ]prices? pharmac\w*|(?-i:\bАНЦ\b|\bANC\b)",
            "Аптека Доброго Дня": r"аптек\w* доброго дня|apteka dobroho dnia|\bdobr[oa]\w* dn[iy]\w*|good day pharmac\w*|\badd\.ua|(?-i:Доброго Дня)",
            # Велика літера й відсутність «!» відрізняють назву мережі від побажання наприкінці відповіді.
            "Бажаємо здоров'я": r"(?-i:Бажаємо [Зз]доров)[’'‘]я(?!\s*!)|bazha\w*\s+zdorov\w*",
            "Аптека оптових цін": r"аптек\w* оптових цін|apteka optovykh tsin|pharmacy of wholesale prices",
            "D.S.": r"аптек\w*\s+[«\"“]?d\.?\s?s\b|(?-i:\bD\.S\.)",
            "Копійка": r"(?-i:Копійк)|kopiyka|kopiika|kopeyka",
            "Tabletki.ua": r"tabletki|таблетки\.(?:ua|юа)",
            "Liki24": r"liki\s?24|ліки\s?24",
        },
        "domains": {
            "Аптека 9-1-1": ["apteka911.ua"],
            "Подорожник": ["podorozhnyk.ua"],
            "АНЦ": ["anc.ua"],
            "Аптека Доброго Дня": ["add.ua"],
            "Tabletki.ua": ["tabletki.ua"],
            "Liki24": ["liki24.com"],
        },
        "queries": [
            ("BEST", "Яка аптека в Україні найкраща?", "Which pharmacy in Ukraine is the best?"),
            ("BEST", "Де краще замовляти ліки онлайн?", "Where is it better to order medicines online?"),
            ("BEST", "Порадь зручний сервіс пошуку ліків.", "Recommend a convenient service for finding medicines."),
            ("BEST", "Яка аптечна мережа має найбільший асортимент?", "Which pharmacy chain has the widest range of products?"),
            ("TASK", "Де забронювати ліки онлайн і забрати в аптеці?", "Where can I reserve medicines online and pick them up at a pharmacy?"),
            ("TASK", "Де замовити ліки з доставкою додому?", "Where can I order medicines with home delivery?"),
            ("TASK", "Де знайти рідкісні ліки в наявності?", "Where can I find rare medicines in stock?"),
            ("TASK", "Де отримати ліки за програмою «Доступні ліки»?", "Where can I get medicines under the 'Affordable Medicines' program?"),
            ("COMP", "Де зручніше купувати ліки — в аптечній мережі чи через агрегатор?", "Is it more convenient to buy medicines from a pharmacy chain or through an aggregator?"),
            ("COMP", "Яка аптека має найзручніший застосунок?", "Which pharmacy has the most convenient app?"),
            ("COMP", "У якій аптеці найкраща програма знижок?", "Which pharmacy has the best discount program?"),
            ("COMP", "Яка аптека доставляє найшвидше?", "Which pharmacy delivers the fastest?"),
            ("PRICE", "Де найдешевші ліки?", "Where are medicines the cheapest?"),
            ("PRICE", "Як порівняти ціни на ліки в різних аптеках?", "How can I compare medicine prices across different pharmacies?"),
            ("PRICE", "У якій аптеці найнижчі ціни на вітаміни?", "Which pharmacy has the lowest prices on vitamins?"),
            ("PRICE", "Де є знижки для пенсіонерів?", "Which pharmacies offer discounts for pensioners?"),
            ("TRUST", "У яких аптеках точно немає підробок?", "Which pharmacies definitely don't sell counterfeit medicines?"),
            ("TRUST", "Якій онлайн-аптеці можна довіряти?", "Which online pharmacy can be trusted?"),
            ("TRUST", "Де можна отримати консультацію фармацевта онлайн?", "Where can I get an online consultation with a pharmacist?"),
            ("TRUST", "Які аптеки працюють цілодобово?", "Which pharmacies are open 24/7?"),
        ],
    },
    "post": {
        "title": "Пошта і логістика",
        "brands": {
            "Нова Пошта": r"нов\w+ пошт(?!ов)|nova\s?po(?:sh|s)hta|nova\s?post\b|\bнп\b",
            "Укрпошта": r"укрпошт|ukrposhta",
            "Meest": r"meest|міст[-\s]?експрес|міст пошт",
            # «delivery» — звичайне англійське слово, тому латиницею рахуємо лише однозначні форми.
            "Delivery": r"делівері|delivery[-\s]auto|delivery\.ua|delivery group|[«\"“]delivery[»\"”]|\*\*delivery\b|delivery\s?/\s?sat\b|sat\s?/\s?delivery\b",
            "САТ": r"\bsat\.ua|(?-i:\bСАТ\b|\bSAT\b)",
        },
        "domains": {
            "Нова Пошта": ["novaposhta.ua", "novapost.com"],
            "Укрпошта": ["ukrposhta.ua"],
            "Meest": ["meest.com", "meest.ua", "meest-express.com.ua"],
            "Delivery": ["delivery-auto.com"],
            "САТ": ["sat.ua"],
        },
        "queries": [
            ("BEST", "Яка служба доставки в Україні найкраща?", "Which parcel delivery service in Ukraine is the best?"),
            ("BEST", "Чим краще відправляти посилки по Україні?", "What is the best way to send parcels within Ukraine?"),
            ("TASK", "Як відправити посилку за кордон?", "How can I send a parcel abroad?"),
            ("TASK", "Чим доставити великогабаритний вантаж?", "Which service should I use to ship oversized cargo?"),
            ("COMP", "Яка служба доставляє найшвидше?", "Which parcel service delivers the fastest?"),
            ("COMP", "У кого зручніші поштомати?", "Which service has more convenient parcel lockers?"),
            ("PRICE", "Якою службою найдешевше відправити посилку?", "Which service is the cheapest for sending a parcel?"),
            ("PRICE", "Де найдешевша доставка з-за кордону?", "Which service offers the cheapest delivery from abroad?"),
            ("TRUST", "Якій службі доставки можна довірити цінну посилку?", "Which delivery service can I trust with a valuable parcel?"),
            ("TRUST", "Яка служба найкраще компенсує пошкоджені посилки?", "Which service compensates best for damaged parcels?"),
        ],
    },
    "food": {
        "title": "Доставка їжі і продуктів",
        "brands": {
            "Glovo": r"glovo|глово",
            "Bolt Food": r"bolt\s?food|болт\s?фуд",
            "Zakaz.ua": r"zakaz\.ua|\bzakaz\b|заказ\.юа",
            "Сільпо": r"сільпо|silpo",
        },
        "domains": {
            "Glovo": ["glovoapp.com"],
            "Bolt Food": ["food.bolt.eu", "bolt.eu"],
            "Zakaz.ua": ["zakaz.ua"],
            "Сільпо": ["silpo.ua"],
        },
        "queries": [
            ("BEST", "Який сервіс доставки їжі найкращий?", "Which food delivery service is the best?"),
            ("BEST", "Де зручно замовляти продукти додому?", "Where is it convenient to order groceries to my home?"),
            ("TASK", "Де замовити продукти із супермаркету з доставкою сьогодні?", "Where can I order supermarket groceries with same-day delivery?"),
            ("TASK", "Де замовити їжу з ресторану пізно ввечері?", "Where can I order restaurant food late in the evening?"),
            ("COMP", "Який сервіс доставки їжі найшвидший?", "Which food delivery service is the fastest?"),
            ("COMP", "У якому сервісі найбільший вибір ресторанів?", "Which service has the largest selection of restaurants?"),
            ("PRICE", "У якому сервісі найдешевша доставка їжі?", "Which service has the cheapest food delivery?"),
            ("PRICE", "Де є підписка на безкоштовну доставку продуктів?", "Which services offer a subscription for free grocery delivery?"),
            ("TRUST", "Який сервіс доставки продуктів привозить свіже?", "Which grocery delivery service brings fresh products?"),
            ("TRUST", "Який сервіс доставки їжі має найкращу підтримку?", "Which food delivery service has the best customer support?"),
        ],
    },
}


# Контрольний власник — іноземна фінансова або корпоративна група (станом на вересень 2026 р.).
# Решта 35 брендів мають українського приватного або державного власника.
FOREIGN_PARENTS = {
    "Райффайзен Банк": "Raiffeisen Bank International (Австрія)",
    "УкрСиббанк": "BNP Paribas (Франція)",
    "OTP Bank": "OTP Bank (Угорщина)",
    "Креді Агріколь": "Crédit Agricole (Франція)",
    "Кредобанк": "PKO Bank Polski (Польща)",
    "Glovo": "Delivery Hero (Німеччина)",
    "Bolt Food": "Bolt Technology (Естонія)",
}
# Український бізнес із мережею за кордоном: окремо перевіряється в аналізі чутливості.
INTERNATIONAL_NETWORK = {"Meest"}
